// scripts/gen-tones.js — Generate app/radio/generated/valid-tones.ts from
// the backend speaker manifests (D:/NEWStool/indienews/backend/data/speakers/*.json).
//
// Run manually after adding/removing a tone in any speaker JSON:
//   npm run gen:tones
//
// Output is committed to git so Cloudflare CI doesn't need access to backend.
//
// The generated TS file exports VALID_TONES (sorted union of all `tones` and
// `tone_fallbacks` keys across all speakers) plus a Tone type alias.

const fs = require('fs')
const path = require('path')

const SPEAKERS_DIR = 'D:/NEWStool/indienews/backend/data/speakers'
// まばたきさせない tone 表。psd_export_characters.py --dump-no-blink が書き出す。
// 元から目を閉じている表情は _blink に差し替えると別の閉じ目になってしまうため。
const NO_BLINK_FILE = path.join(SPEAKERS_DIR, 'no_blink.json')
const OUT_FILE = path.join(__dirname, '..', 'app', 'radio', 'generated', 'valid-tones.ts')

function collectTones() {
  const files = fs.readdirSync(SPEAKERS_DIR).filter((f) => f.endsWith('.json'))
  if (files.length === 0) {
    throw new Error(`No speaker JSON found in ${SPEAKERS_DIR}`)
  }

  const tones = new Set()
  const fallbacks = new Set()
  for (const f of files) {
    const raw = fs.readFileSync(path.join(SPEAKERS_DIR, f), 'utf-8')
    const data = JSON.parse(raw)
    for (const k of Object.keys(data.tones || {})) {
      if (!k.startsWith('_')) tones.add(k)
    }
    for (const k of Object.keys(data.tone_fallbacks || {})) {
      if (!k.startsWith('_')) fallbacks.add(k)
    }
  }

  // Frontend only renders <speaker>/<tone>.png. Fallback target tones must be
  // in the canonical tones set (since they resolve to a real PSD); the
  // fallback *source* keys (e.g. 'chuuni' on zunda) ARE valid input tones from
  // segments and must be in VALID_TONES too so the type check passes.
  const union = new Set([...tones, ...fallbacks])
  return Array.from(union).sort()
}

function collectNoBlink() {
  if (!fs.existsSync(NO_BLINK_FILE)) {
    throw new Error(
      `${NO_BLINK_FILE} not found. Run:\n` +
        `  python backend/tools/psd_export_characters.py --dump-no-blink`
    )
  }
  return JSON.parse(fs.readFileSync(NO_BLINK_FILE, 'utf-8'))
}

function main() {
  const tones = collectTones()
  const noBlink = collectNoBlink()
  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true })

  const header =
    `// AUTO-GENERATED by scripts/gen-tones.js — do not edit by hand.\n` +
    `// Source: D:/NEWStool/indienews/backend/data/speakers/*.json\n` +
    `// Run \`npm run gen:tones\` after editing any speaker manifest.\n\n`

  const body =
    `export const VALID_TONES = [\n` +
    tones.map((t) => `  '${t}',`).join('\n') +
    `\n] as const\n\n` +
    `export type Tone = typeof VALID_TONES[number]\n\n` +
    `// 元から目を閉じている表情。まばたきさせると「閉じ目 -> 別の閉じ目」の\n` +
    `// 切り替えになり、まばたきではなく表情が一瞬変わってしまうので目パチを止める。\n` +
    `// Source: backend/data/speakers/no_blink.json\n` +
    `//   (python backend/tools/psd_export_characters.py --dump-no-blink)\n` +
    `export const NO_BLINK: Record<string, readonly string[]> = {\n` +
    Object.keys(noBlink)
      .sort()
      .map((k) => `  ${k}: [${noBlink[k].map((t) => `'${t}'`).join(', ')}],`)
      .join('\n') +
    `\n}\n`

  fs.writeFileSync(OUT_FILE, header + body, 'utf-8')
  const nb = Object.values(noBlink).reduce((n, v) => n + v.length, 0)
  console.log(`Wrote ${OUT_FILE} (${tones.length} tones, ${nb} no-blink entries)`)
}

main()
