// scripts/gen-tones.js — Generate app/radio/generated/valid-tones.ts from
// the backend speaker manifests (D:/NEWStool/indienews/backend/data/speakers/*.json).
//
// Run manually after adding/removing a tone in any speaker JSON:
//   npm run gen:tones
//
// Output is committed to git so Cloudflare CI doesn't need access to backend.
//
// The generated TS file exports VALID_TONES (sorted union of all `tones` and
// `tone_fallbacks` keys across all speakers) plus a Tone type alias.

const fs = require('fs')
const path = require('path')

const SPEAKERS_DIR = 'D:/NEWStool/indienews/backend/data/speakers'
const OUT_FILE = path.join(__dirname, '..', 'app', 'radio', 'generated', 'valid-tones.ts')

function collectTones() {
  const files = fs.readdirSync(SPEAKERS_DIR).filter((f) => f.endsWith('.json'))
  if (files.length === 0) {
    throw new Error(`No speaker JSON found in ${SPEAKERS_DIR}`)
  }

  const tones = new Set()
  const fallbacks = new Set()
  for (const f of files) {
    const raw = fs.readFileSync(path.join(SPEAKERS_DIR, f), 'utf-8')
    const data = JSON.parse(raw)
    for (const k of Object.keys(data.tones || {})) {
      if (!k.startsWith('_')) tones.add(k)
    }
    for (const k of Object.keys(data.tone_fallbacks || {})) {
      if (!k.startsWith('_')) fallbacks.add(k)
    }
  }

  // Frontend only renders <speaker>/<tone>.png. Fallback target tones must be
  // in the canonical tones set (since they resolve to a real PSD); the
  // fallback *source* keys (e.g. 'chuuni' on zunda) ARE valid input tones from
  // segments and must be in VALID_TONES too so the type check passes.
  const union = new Set([...tones, ...fallbacks])
  return Array.from(union).sort()
}

function main() {
  const tones = collectTones()
  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true })

  const header =
    `// AUTO-GENERATED by scripts/gen-tones.js — do not edit by hand.\n` +
    `// Source: D:/NEWStool/indienews/backend/data/speakers/*.json\n` +
    `// Run \`npm run gen:tones\` after editing any speaker manifest.\n\n`

  const body =
    `export const VALID_TONES = [\n` +
    tones.map((t) => `  '${t}',`).join('\n') +
    `\n] as const\n\n` +
    `export type Tone = typeof VALID_TONES[number]\n`

  fs.writeFileSync(OUT_FILE, header + body, 'utf-8')
  console.log(`Wrote ${OUT_FILE} (${tones.length} tones)`)
}

main()
